global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pspd-lab-monitor'
    environment: 'development'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'url-shortener-rest'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['url-shortener-rest:8083']

  - job_name: 'qr-generator-rest'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['qr-generator-rest:8082']

  - job_name: 'microservice-a-grpc'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['microservice-a-grpc:8080']

  - job_name: 'microservice-b-grpc'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['microservice-b-grpc:8081']
